function changelang(){
var home=document.getElementById('home');
var about=document.getElementById('about_href');
var products=document.getElementById('products');
var sign=document.getElementById('sign');
var blog=document.getElementById('blog');
var aboutus=document.getElementById('aboutus');
var team=document.getElementById('team');
var testimonials=document.getElementById('testimonials');
var DeepDropDown=document.getElementById('DeepDropDown');
var DeepDropDown1=document.getElementById('DeepDropDown1');
var DeepDropDown2=document.getElementById('DeepDropDown2')
var DeepDropDown3=document.getElementById('DeepDropDown3')
var DeepDropDown4=document.getElementById('DeepDropDown4')
var DeepDropDown5=document.getElementById('DeepDropDown5')
var text1=document.getElementById('text1')
var text2=document.getElementById('text2')
var text3=document.getElementById('text3')
var title_link=document.getElementById('title_link')
var linkhome=document.getElementById('link_home')
var linkaboutus=document.getElementById('link_aboutus')
var linkservice=document.getElementById('link_sevice')
var linkterms=document.getElementById('link_terms')
var linkprivacy=document.getElementById('link_privacy')
var title_service=document.getElementById('title_service')
var Web_Design=document.getElementById('Web_Design')
var Web_Applications=document.getElementById('Web_Applications')
var Web_development=document.getElementById('Web_development')
var marketing=document.getElementById('marketing')
var graphics=document.getElementById('graphics')
var title_address=document.getElementById('title_address')
var company=document.getElementById("address")
var phone=document.getElementById('phone')
    home.innerHTML="خانه"
    about.innerHTML="درباره"
    products.innerHTML="محصولات"
    sign.innerHTML="ورود"
    blog.innerHTML="وبلاگ"
    aboutus.innerHTML="درباره ما"
    team.innerHTML="تیم مان"
    testimonials.innerHTML="گواهینامه ها"
    DeepDropDown.innerHTML="لیست کشویی"
    DeepDropDown1.innerHTML="لیست کشویی1"
    DeepDropDown2.innerHTML="لیست کشویی2"
    DeepDropDown3.innerHTML="لیست کشویی3"
    DeepDropDown4.innerHTML="لیست کشویی 4"
    text1.innerHTML="زیما یک شرکت دانش بنیان است که در حوزه بیوتکنولوژی فعالیت می کند.این شرکت حدود 8 سال است که فعالیت می کند.</br>این شرکت هم اکنون با مدیریت مهندس رضایی در پارک فناوری پردیس فعالیت می کند. "
    text2.innerHTML="سلام من ابوالفضل حسین زاده هستم. من کارآموز برنامه نویسی فرانت اند<br> و دانشجوی دانشگاه علم و صنعت ایران هستم. امیدوارم از کارم لذت ببری. "
    text3.innerHTML="این پروژه برای ایجاد یک صفحه وب است که باید به درستی کار کند. من برای این پروژه<br>از سایت های قالب آماده استفاده کردم.البته این پروژه کپی قالب آماده نیست بلکه مدلی از آن سایت هاست."
    text2.style.left ="35%";
    text3.style.left="30%";
    title_link.innerHTML="لینک های مفید"
    linkhome.innerHTML="خانه"
    linkaboutus.innerHTML="درباره ما"
    linkterms.innerHTML="شرایط خدمات"
    linkservice.innerHTML="سرویس ها"
    linkprivacy.innerHTML="سیاست حفظ حریم خصوصی"
    title_service.innerHTML="سرویس ها"
    Web_Design.innerHTML="طراحی سایت"
    Web_Applications.innerHTML="وب اپلیکیشن"
    marketing.innerHTML="بازاریابی"
    graphics.innerHTML="گرافیک"
    Web_development.innerHTML="برنامه نویس"
    company.innerHTML="<h2>شرکت</h2><br>تهران ؛پردیس؛<br>پارک علم وفاوری"
    phone.innerHTML="تلفن:0210000000000000<br>Email:email@gmail.com"
    phone.style.left="-220px"
}
